//
// Created by ianpo on 25/01/2025.
//

#pragma once

#define VXM_VERTEX_TYPE 					"__TYPE_VERTEX_SHADER__"
#define VXM_FRAGMENT_TYPE 					"__TYPE_FRAGMENT_SHADER__"
#define VXM_PIXEL_TYPE 						"__TYPE_PIXEL_SHADER__"
#define VXM_GEOMETRY_TYPE 					"__TYPE_GEOMETRY_SHADER__"
#define VXM_COMPUTE_TYPE 					"__TYPE_COMPUTE_SHADER__"
#define VXM_TESS_CONTROL_SHADER_TYPE 		"__TYPE_TESS_CONTROL_SHADER__"
#define VXM_TESS_EVALUATION_SHADER_TYPE		"__TYPE_TESS_EVALUATION_SHADER__"